export const demoUser = {
  id: 1,
  name: 'Ahmed Hassan',
  email: 'ahmed@uyho.org',
  avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBcx1dqVVbaHZAObrk4w2IV2ailmUB5yQw8EjADoQgy-tXZE_UTDAdQb3m3ORSZUPgy0u9rx8IthPp_6rFnRXjgzhbRyftVzQiJwQibYQccl4D2jHjSi_62KB9ok5qzztMk-JT0g5p3ydhYvZ65p05RJqsYi5v5W2gV-12iU4wyhkOXde0525IYzhCS4_Vy5_dtnBvuh8ahf3J3PjAx3fRkWlTwm-XQ-qX2-34yyNy5xThkj2ajcsspUufYAPNsq104sdDcOQVNbmnq',
  role: 'Active Volunteer',
  totalHours: 124,
  projects: 12,
  points: 2400,
  joinedDate: '2023-06-15',
  status: 'Active',
}

export const demoCampaigns = [
  {
    id: 1,
    title: 'Flood Relief Logistics',
    description: 'Immediate help needed to coordinate water distribution in the North zone.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDCHv7XDW4Thn97rKMEeNFQ_zQwwwZbsf1qrRu24-36CkctMnJpmEQYKRndI0JtDQD8ZNlS_sEr8IREtee9pZHhOqkuaZiGeDjGn5uyuBtbld4undu81bTPFSxUNdGTikS251LfM42cAAzhDA-GfhBf8dkPurEeKf-SMi5yvrNdSoEvMHP-sZRqR1uzGSkcyX8daqBz0E0Rpos09i45n1QMelbHJAWxP4egCiSXEMOyYVyl7HYsAQjirxZgN7H6lMqk6xyt5ekrlnj5',
    location: 'North Zone District',
    status: 'Urgent',
    urgency: true,
    hoursRequired: 2,
    volunteersNeeded: 15,
    volunteersJoined: 8,
    category: 'Disaster Relief',
  },
  {
    id: 2,
    title: 'School Education Drive',
    description: 'Help teach underprivileged children basic math and English skills.',
    image: 'https://images.unsplash.com/photo-1427504494785-cddbde40e6b9?w=400',
    location: 'Central District',
    status: 'Active',
    urgency: false,
    hoursRequired: 4,
    volunteersNeeded: 10,
    volunteersJoined: 7,
    category: 'Education',
  },
  {
    id: 3,
    title: 'Healthcare Awareness',
    description: 'Conduct health checkup camps and provide health awareness sessions.',
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400',
    location: 'Southern Village',
    status: 'Active',
    urgency: false,
    hoursRequired: 3,
    volunteersNeeded: 8,
    volunteersJoined: 5,
    category: 'Healthcare',
  },
]

export const demoPrograms = [
  {
    id: 1,
    title: 'Basic Digital Skills',
    description: 'Learn fundamental computer literacy and digital tools.',
    status: 'Ongoing',
    progress: 65,
    startDate: '2024-01-15',
    endDate: '2024-03-15',
    participants: 24,
    category: 'Training',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400',
  },
  {
    id: 2,
    title: 'Leadership Development',
    description: 'Advanced training for volunteer leaders and coordinators.',
    status: 'Ongoing',
    progress: 45,
    startDate: '2024-01-01',
    endDate: '2024-04-01',
    participants: 15,
    category: 'Development',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400',
  },
  {
    id: 3,
    title: 'Community Healthcare Program',
    description: 'Monthly health checkup camps and awareness sessions.',
    status: 'Planning',
    progress: 20,
    startDate: '2024-02-01',
    endDate: '2024-12-31',
    participants: 8,
    category: 'Healthcare',
    image: 'https://images.unsplash.com/photo-1579154204601-01d82b27c9d0?w=400',
  },
]

export const demoLeaderboard = [
  { id: 1, name: 'Fatima Khan', hours: 245, points: 5800, rank: 1, avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200' },
  { id: 2, name: 'Ahmed Hassan', hours: 124, points: 2400, rank: 2, avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBcx1dqVVbaHZAObrk4w2IV2ailmUB5yQw8EjADoQgy-tXZE_UTDAdQb3m3ORSZUPgy0u9rx8IthPp_6rFnRXjgzhbRyftVzQiJwQibYQccl4D2jHjSi_62KB9ok5qzztMk-JT0g5p3ydhYvZ65p05RJqsYi5v5W2gV-12iU4wyhkOXde0525IYzhCS4_Vy5_dtnBvuh8ahf3J3PjAx3fRkWlTwm-XQ-qX2-34yyNy5xThkj2ajcsspUufYAPNsq104sdDcOQVNbmnq' },
  { id: 3, name: 'Karim Rana', hours: 98, points: 1800, rank: 3, avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200' },
  { id: 4, name: 'Saira Ahmed', hours: 87, points: 1650, rank: 4, avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200' },
  { id: 5, name: 'Raihan Khan', hours: 76, points: 1420, rank: 5, avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200' },
]

export const demoWings = [
  {
    id: 1,
    name: 'Education Wing',
    description: 'Focused on providing quality education to underprivileged children.',
    head: 'Fatima Khan',
    members: 24,
    color: 'bg-blue-500',
    icon: 'school',
  },
  {
    id: 2,
    name: 'Healthcare Wing',
    description: 'Dedicated to improving health awareness and medical support.',
    head: 'Dr. Ahmed',
    members: 18,
    color: 'bg-red-500',
    icon: 'health_and_safety',
  },
  {
    id: 3,
    name: 'Disaster Relief Wing',
    description: 'Rapid response team for emergency situations and disasters.',
    head: 'Karim Rana',
    members: 15,
    color: 'bg-orange-500',
    icon: 'emergency',
  },
  {
    id: 4,
    name: 'Community Development Wing',
    description: 'Building sustainable community projects and initiatives.',
    head: 'Saira Ahmed',
    members: 20,
    color: 'bg-green-500',
    icon: 'groups',
  },
]

export const demoChats = [
  {
    id: 1,
    name: 'Education Wing Team',
    lastMessage: 'Great work on the literacy program!',
    timestamp: '2 hours ago',
    unread: 2,
    type: 'group',
    avatar: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=100',
  },
  {
    id: 2,
    name: 'Fatima Khan',
    lastMessage: 'Can you help with tomorrow\'s event?',
    timestamp: '30 mins ago',
    unread: 1,
    type: 'direct',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100',
  },
  {
    id: 3,
    name: 'Disaster Relief Coordinators',
    lastMessage: 'Emergency response drill scheduled for Friday',
    timestamp: 'Yesterday',
    unread: 0,
    type: 'group',
    avatar: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=100',
  },
]

export const demoActivities = [
  {
    id: 1,
    type: 'joined',
    title: 'Joined Flood Relief Campaign',
    timestamp: '2 hours ago',
    icon: 'check_circle',
  },
  {
    id: 2,
    type: 'completed',
    title: 'Completed 8 hours volunteering',
    timestamp: '5 hours ago',
    icon: 'done_all',
  },
  {
    id: 3,
    type: 'achievement',
    title: 'Achieved 100 Hours Milestone',
    timestamp: '1 day ago',
    icon: 'trophy',
  },
]
